#!/bin/sh
if [ "`dirname $0`" = "." ]; then
  ADJFIELD=./adjfield
  RUNFORM=../runform/runform
  FORMAXFRM=formax.frm
  TRIGGRFRM=trigger.frm
  LOGGING=-g/tmp/formax.log
else
  ADJFIELD=adjfield
  RUNFORM=runform
  FORMAXFRM=${ARX:-/opt/arx}/lib/formax.frm
  TRIGGRFRM=${ARX:-/opt/arx}/lib/trigger.frm
  LOGGING=""
fi
FORM=$1
if ! cp -v $FORM.frm $FORM.frm.bac; then
  echo "$FORM.frm not found" >&2
  exit 2
fi
SQL="sqlite3 -batch $FORM.frm"
$SQL "select mtext from maps where page_id = 4 order by line" >$FORM.map
${EDITOR:-vi} $FORM.map
$SQL "delete from maps where page_id = 4"
LINE=0
IFS=% sed "s/^/'/;s/\$/'/" $FORM.map | while read TEXT; do
  LINE=`expr $LINE + 1`
  $SQL "insert into maps (page_id, line, mtext) values (4, $LINE, $TEXT)"
done
$ADJFIELD <$FORM.map | $SQL
rm $FORM.map
$RUNFORM $LOGGING -x $FORMAXFRM $FORM.frm
$RUNFORM $LOGGING -x $TRIGGRFRM $FORM.frm
$SQL .dump >$FORM.inp
${EDITOR:-vi} $FORM.inp
rm $FORM.frm
$SQL <$FORM.inp
exit
