#!/bin/sh
FORM=$1
if ! cp -v $FORM.frm $FORM.frm.bac; then
  echo "$FORM.frm not found" >&2
  exit 2
fi
SQL="sqlite3 -batch $FORM.frm"
$SQL "select mtext from maps order by line" >$FORM.map
${EDITOR:-vi} $FORM.map
$SQL "delete from maps"
LINE=0
IFS=% sed "s/^/'/;s/\$/'/" $FORM.map | while read TEXT; do
  LINE=`expr $LINE + 1`
  $SQL "insert into maps (line, mtext) values ($LINE, $TEXT)"
done
${ARX:-/opt/arx}/bin/adjfield <$FORM.map | $SQL
rm $FORM.map
$SQL .dump >$FORM.inp
${EDITOR:-vi} $FORM.inp
rm $FORM.frm
$SQL <$FORM.inp
exit
