#!/bin/sh
USAGE="makeform name title table cols... >name.inp"
FORM=$1
TITLE=$2
TABLE=$3
shift 3
cat <<EOF
#PRAGMA encoding="ISO-8859-15";
`./extractsql ../runform/form.h`
`./extractsql ../runform/rerror.h`
`./extractsql ../runform/rblock.h`
`./extractsql ../runform/rfield.h`
`./extractsql ../runform/rmap.h`
`./extractsql ../runform/rpage.h`
INSERT INTO forms  (id, name, title) VALUES (1, '$FORM', '$TITLE');
INSERT INTO blocks (form_id, name) VALUES (1, '$TABLE');
INSERT INTO blocks (id, form_id, name) VALUES (0, 1, 'dual');
INSERT INTO pages  (form_id, name) VALUES (1, '$TABLE-0');
INSERT INTO pages  (id, form_id, name, ysiz, vwpy0, border) VALUES (0, 1, 'formax', 1, 0, 0);
EOF
LINE=1
for COLUMN; do
if [ $LINE = 1 ]; then KEY=1; else KEY=0; fi
  cat <<EOF
INSERT INTO maps (page_id, line, mtext) VALUES (1, $LINE+1, ' [$LINE]$COLUMN');
INSERT INTO fields (seq, name, line, key) VALUES ($LINE, '$COLUMN', $LINE+1, $KEY);
EOF
  LINE=`expr $LINE + 1`
done
LINE=`expr $LINE + 1`
  cat <<EOF
INSERT INTO maps (page_id, line, mtext) VALUES (1, $LINE+1, ' F7 Query');
EOF
LINE=`expr $LINE + 1`
  cat <<EOF
INSERT INTO maps (page_id, line, mtext) VALUES (1, $LINE+1, ' Enter Commit');
EOF
LINE=`expr $LINE + 1`
exit
