#!/bin/sh
USAGE="makeform name title table cols... >name.inp"
FORM=$1
TITLE=$2
TABLE=$3
shift 3

helpmap() {
LINE=`expr $LINE + 1`
  cat <<EOF
INSERT INTO maps (page_id, line, mtext) VALUES (1, $LINE, ' $1');
EOF
}

guidmap() {
LINE=`expr $LINE + 1`
  cat <<EOF
UPDATE maps set mtext = mtext || '                            $1' where line = $LINE;
EOF
}

cat <<EOF
#PRAGMA encoding="ISO-8859-15";
`./extractsql ../runform/form.h`
`./extractsql ../runform/rerror.h`
`./extractsql ../runform/rblock.h`
`./extractsql ../runform/rfield.h`
`./extractsql ../runform/rmap.h`
`./extractsql ../runform/rpage.h`
INSERT INTO forms  (id, name, title) VALUES (1, '$FORM', '$TITLE');
INSERT INTO blocks (form_id, name) VALUES (1, '$TABLE');
INSERT INTO blocks (id, form_id, name) VALUES (0, 1, 'dual');
INSERT INTO pages  (form_id, name) VALUES (1, '$TABLE-0');
INSERT INTO pages  (id, form_id, name, ysiz, vwpy0, border) VALUES (0, 1, 'formax', 1, 0, 0);
INSERT INTO maps   (page_id, line, mtext) VALUES (1, 1, '         ');
EOF
LINE=1
for COLUMN; do
if [ $LINE = 1 ]; then KEY=1; else KEY=0; fi
  cat <<EOF
INSERT INTO maps (page_id, line, mtext) VALUES (1, $LINE+1, ' [$LINE]$COLUMN');
INSERT INTO fields (seq, name, line, key) VALUES ($LINE, '$COLUMN', $LINE+1, $KEY);
EOF
  LINE=`expr $LINE + 1`
done
LINE=`expr $LINE + 1`
#elpmap 'F2    Ctrl+c Copy'
#elpmap 'F3    Ctrl+v Paste'
#elpmap 'F5    Ctrl+t Copy-Record'

helpmap 'Right Ctrl+f Edit-Pos1        Edit:   Edit with "Left/Right" and characters'
helpmap 'Left  Ctrl+b Edit-End'
helpmap 'Down  Ctrl+n Next-Record      Update: Move to the record and field with'
helpmap 'Up    Ctrl+p Previous-Record          "Up/Down" and "Tab" and edit'
helpmap 'Enter Ctrl+m Execute'
helpmap 'F6    Ctrl+o Insert-Record    Insert: Press "Insert" or Ctrl-o'
helpmap 'F7    Ctrl+k Delete-Record    Delete: Move to the record'
helpmap 'F8    Ctrl+z Exit                     Press "Delete" or Ctrl-k'
helpmap 'F9    Ctrl+y Quit'          
helpmap 'F10   Ctrl+x Query            Query:  Edit conditions in each field'

LINE=0
guidmap '   Query examples'
guidmap '      >7700'
guidmap '   ~jon'
guidmap '     MANAGER,SALESMAN'
guidmap ''
guidmap '02/18/80-11/30/81'
guidmap '     2000-3000'

exit
