#!/bin/sh
USAGE="makeform name title table cols... >name.inp"
if [ ! "$4" ]; then echo $USAGE >&2; exit 2; fi
PATH=`dirname $0`:$PATH
FORM=$1
TITLE=$2
TABLE=$3
shift 3
cat <<EOF
#PRAGMA encoding="ISO-8859-15";
`extractsql $ARX/runform/form.h`
`extractsql $ARX/runform/rerror.h`
`extractsql $ARX/runform/rblock.h`
`extractsql $ARX/runform/rfield.h`
`extractsql $ARX/runform/rmap.h`
`extractsql $ARX/runform/rpage.h`
`extractsql $ARX/runform/rtrigger.h`
INSERT INTO forms  (id, name, title) VALUES (1, '$FORM', '$TITLE');
INSERT INTO blocks (form_id, name) VALUES (1, '$TABLE');
INSERT INTO blocks (id, form_id, name) VALUES (0, 1, 'dual');
INSERT INTO pages  (form_id, seq, name) VALUES (0, 1, 'formax');
INSERT INTO maps   (page_id, line, mtext) VALUES (4, 1, '         ');
EOF
LINE=0
FLDN=0
for COLUMN; do
  LINE=`expr $LINE + 1`
  FLDN=`expr $FLDN + 10`
  if [ $LINE = 1 ]; then KEY=1; else KEY=0; fi
  echo "INSERT INTO fields (seq, name, line, key) VALUES ($FLDN, '$COLUMN', $LINE+1, $KEY);"
  printf "INSERT INTO maps (page_id, line, mtext) VALUES (4, $LINE+1, ' [$LINE]%-14s \$${LINE}__________________');\\n" $COLUMN
done
exit
