#!/bin/sh
helpmap() {
LINE=`expr $LINE + 1`
echo "INSERT INTO maps (page_id, line, mtext) VALUES (4, $LINE, ' $1');"
}
guidmap() {
LINE=`expr $LINE + 1`
echo "UPDATE maps set mtext = mtext || ' $1' where page_id = 4 and line = $LINE;"
}
ARX=`pwd`/.. sh ./makeform scotty formax1 emps id ename job mgr hiredate sal comm dept_id
  cat <<EOF
UPDATE fields set help = 'Employees last name' where id=2;
UPDATE fields set ftype = 2, dlen = 4, len = 4, low = 7000, high = 8999, valpatn = '\d\d\d\d' where id=4;
UPDATE fields set ftype = 4 where id=5;
UPDATE fields set upd = 0 where id=6;
UPDATE fields set ftype = 2, dlen = 1, len = 1, low = 0, high = 1 where id=7;
INSERT INTO maps (page_id, line, mtext) VALUES (1102, 1, 'next_item();0;');
INSERT INTO maps (page_id, line, mtext) VALUES (1101, 1, 'nav0 + 3;');
INSERT INTO maps (page_id, line, mtext) VALUES (1100, 1, 'cb + cf + String(cr);');
INSERT INTO triggers (form_id, trgfld, trgtyp, page_id) VALUES (1,0,10001,1102); /* #define TRT_ENTERFORM  10001 */
INSERT INTO triggers (form_id, trgfld, trgtyp, page_id) VALUES (1,7,10002,1101); /* #define TRT_NEXTITEM   10002 */
INSERT INTO triggers (form_id, trgfld, trgtyp, page_id) VALUES (1,8,10003,1100); /* #define TRT_EDITFIELD  10003 */
EOF
LINE=9
LINE=`expr $LINE + 1`
#elpmap 'F2    Ctrl+c Copy'
#elpmap 'F3    Ctrl+v Paste'
#elpmap 'F5    Ctrl+t Copy-Record'
helpmap 'Right Ctrl+f Edit-Pos1        Edit:   Edit with "Left/Right" and characters'
helpmap 'Left  Ctrl+b Edit-End'
helpmap 'Down  Ctrl+n Next-Record      Update: Move to the record and field with'
helpmap 'Up    Ctrl+p Previous-Record          "Up/Down" and "Tab" and edit'
helpmap 'Enter Ctrl+m Execute'
helpmap 'F6    Ctrl+o Insert-Record    Insert: Press "Insert" or Ctrl-o'
helpmap 'F7    Ctrl+d Delete-Record    Delete: Move to the record'
helpmap 'F8    Ctrl+z Exit                     Press "Delete" or Ctrl-d'
helpmap 'F9    Ctrl+y Quit'          
helpmap 'F10   Ctrl+x Query            Query:  Edit conditions in each field'
LINE=0
guidmap '                              Query examples Enter to execute'
guidmap '>7700'
guidmap '~jon'
guidmap 'MANAGER,SALESMAN'
guidmap ''
guidmap '02/18/80-11/30/81'
guidmap '2000-3000'
exit
