#!/bin/sh
helpmap() {
LINE=`expr $LINE + 1`
echo "INSERT INTO maps (page_id, line, mtext) VALUES (4, $LINE+1, ' $1');"
}
guidmap() {
LINE=`expr $LINE + 1`
echo "UPDATE maps set mtext = mtext || ' $1' where page_id = 4 and line = $LINE;"
}
ARX=`pwd`/.. sh ./makeform scotty formax1 emps id ename job mgr hiredate sal comm dept_id
  cat <<EOF
INSERT INTO blocks (form_id, name, seq) VALUES (1, 'depts', 50);
INSERT INTO fields VALUES(9,1,5,1,'id',1,0,30,2,1,1,'',8,40,1,1,1,1,0,0,'',0,0,0,0,'','');
INSERT INTO fields VALUES(10,1,5,1,'dname',1,0,30,10,1,0,'',8,43,1,1,1,1,0,0,'',0,0,0,0,'','');
INSERT INTO fields VALUES(11,1,5,1,'loc',1,0,30,22,1,0,'',8,55,1,1,1,1,0,0,'',0,0,0,0,'','');
UPDATE fields set help = 'Employees last name' where id=2;
UPDATE fields set ftype = 2, dlen = 4, len = 4, low = 7000, high = 8999, valpatn = '\d\d\d\d' where id=4;
UPDATE fields set ftype = 4 where id=5;
UPDATE fields set upd = 0 where id=6;
UPDATE fields set ftype = 2, dlen = 1, len = 1, low = 0, high = 1 where id=7;
INSERT INTO maps (page_id, line, mtext) VALUES (2001, 1, 'next_item();0;');
INSERT INTO maps (page_id, line, mtext) VALUES (2002, 1, 'Message("trg:10002,1101");nav0 + 3;');
INSERT INTO maps (page_id, line, mtext) VALUES (2003, 1, 'SQL("select 9001");');
INSERT INTO triggers (form_id, trgfld, trgtyp, page_id) VALUES (1,0,1000,2001);
INSERT INTO triggers (form_id, trgfld, trgtyp, page_id) VALUES (1,7,1001,2002);
INSERT INTO triggers (form_id, trgfld, trgtyp, page_id) VALUES (1,8,1005,2003);
EOF
LINE=9
#elpmap 'F2    Ctrl+c Copy'
#elpmap 'F3    Ctrl+v Paste'
#elpmap 'F5    Ctrl+t Copy-Record'
helpmap 'Right Ctrl+f Edit-Pos1        Edit:   Edit with "Left/Right" and characters'
helpmap 'Left  Ctrl+b Edit-End'
helpmap 'Down  Ctrl+n Next-Record      Update: Move to the record and field with'
helpmap 'Up    Ctrl+p Previous-Record          "Up/Down" and "Tab" and edit'
helpmap 'Enter Ctrl+m Execute'
helpmap 'F6    Ctrl+o Insert-Record    Insert: Press "Insert" or Ctrl-o'
helpmap 'F7    Ctrl+d Delete-Record    Delete: Move to the record'
helpmap 'F8    Ctrl+z Exit                     Press "Delete" or Ctrl-d'
helpmap 'F9    Ctrl+y Quit'          
helpmap 'F10   Ctrl+x Query            Query:  Edit conditions in each field'
LINE=-1
guidmap '                              Query examples Enter to execute'
guidmap '>7700'
guidmap '~jon'
guidmap 'MANAGER,SALESMAN'
guidmap ''
guidmap '02/18/80-11/30/81'
guidmap '2000-3000'
guidmap '$9_ $10_______ $11____________________'
exit
