remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: formax
url: https://formax.freakout.de
show_downloads: true
show_edgerelease: false
show_archrelease: false
show_footer: false
logo: /assets/logo.jpg
edgerelease: "1.2.0"
latestrel: "1.2.0"
archrelease: "1.0.0"
