#!/bin/sh
sudo apt-get -y update
sudo apt-get -y install build-essential
sudo apt-get -y install python
sudo apt-get -y install unixodbc
sudo apt-get -y install libsqliteodbc
sudo apt-get -y install libncurses5-dev
sudo apt-get -y install flex
./configure
make
sudo make install
. /etc/profile.d/arx.sh
mkdir myform
cd myform
sqlite3 mydb.sq3 <'EOF'
create table depts (id integer primary key not null, dname text, loc text);
insert into depts values (10, 'ACCOUNTING', 'NEW YORK');
insert into depts values (20, 'RESEARCH',   'DALLAS');
insert into depts values (30, 'SALES',      'CHICAGO');
insert into depts values (40, 'OPERATIONS', 'BOSTON');
EOF
makeform deptform Departments depts id dname loc | sqlite3 myform.frm
runform myform.frm mydb.sq3
editform myform
runform myform.frm mydb.sq3
exit
